language: c

dist: bionic
os: linux

notifications:
  email: false

before_install:
- sudo apt-get install build-essential cmake iverilog tk binutils-msp430 gcc-msp430 msp430-libc msp430mcu expect-dev verilator -y

install:
- mkdir build && cd build && cmake .. $ATOM && cd ..

script:
- cd core/sim/rtl_sim/run/
- ./$TARGET

env:
  - TARGET=run_all          ATOM=-DATOMICITY_MONITOR=0
  - TARGET=run_all          ATOM=-DATOMICITY_MONITOR=1
  - TARGET=run_all_sancus   ATOM=-DATOMICITY_MONITOR=0
  - TARGET=run_all_sancus   ATOM=-DATOMICITY_MONITOR=1

jobs: # Add jobs that only compile but do not run the tests.
  include:
    - name: "Only compile, bionic"
      script: cd build && cmake --build .
    - name: "Only compile, focal"
      dist: focal
      os: linux
      script: cd build && cmake --build .
